#!/bin/sh
#$Id: pdf2text,v 17.0 2002/11/23 01:29:09 raman Exp $
#

if which pdftotext   > /dev/null
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext $tempfile - | cat -s 
    rm -f $tempfile
    exit 0
else 
    echo "pdftotext not found --install package XPDF."
    exit 1
fi
