#!/bin/sh
#$Id: pdf2text,v 23.505 2005/11/25 16:30:52 raman Exp $
#

if which pdftotext   > /dev/null
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext $tempfile - | cat -s 
    rm -f $tempfile
    exit 0
else 
    echo "pdftotext not found --install package XPDF."
    exit 1
fi
