#!/bin/sh
#$Id: pdf2text,v 18.0 2003/04/29 21:20:54 raman Exp $
#

if which pdftotext   > /dev/null
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext $tempfile - | cat -s 
    rm -f $tempfile
    exit 0
else 
    echo "pdftotext not found --install package XPDF."
    exit 1
fi
