#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/emacspeak

FLAVOR=$1
PACKAGE=emacspeak

echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}

if [ ${FLAVOR} != emacs ]; then
    rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
else
    cd /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
    find lisp \( -name \*.elc -o -name \*-cus-load.el -o -name \*-loaddefs.el \) -delete
    rm -f lisp/emacspeak-finder-inf.el .nosearch compile.log.gz
fi
