#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/emacspeak

FLAVOR=$1
PACKAGE=emacspeak

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}
ELDIR_REL=../../../emacs/site-lisp/${PACKAGE}

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

case "$FLAVOR" in
    emacs1*|emacs2[0123])
        echo "  ${PACKAGE} does not support ${FLAVOR}"
        exit 0
        ;;
    xemacs*)
        echo "  ${PACKAGE} does not support xemacs"
        exit 0
        ;;
    emacs*)
        SITEFLAG="--no-site-file"
        ;;
    *)
        echo "unknown flavor $FLAVOR, does not start with emacs or xemacs"
	exit 1
        ;;
esac

# Prevent gnupg to write to /root/.gnupg which leaves files behind on purge
export GNUPGHOME=`mktemp -d /tmp/gnupg.XXXXXX`

if [ -d ${ELCDIR} ]; then
    if [ ${FLAVOR} = emacs ]
    then find ${ELCDIR}/lisp \( -name '*.elc' -o -name '*-cus-load.el' -o -name '*-loaddefs.el' \) -delete
    else rm -rf ${ELCDIR}/lisp
    fi
    rm -f ${ELCDIR}/compile.log.gz
fi

install -m 755 -d ${ELCDIR}/lisp/g-client

cd ${ELCDIR}/lisp
if [ ${FLAVOR} != emacs ]; then
    find ../${ELDIR_REL}/lisp \( -name '*.el' -o -name Makefile \) -maxdepth 1 -exec ln -s {} \; 2>/dev/null
fi
for file in *.elc
do [ -e "${file%.elc}.el" ] || rm -f $file
done

cd g-client
if [ ${FLAVOR} != emacs ]; then
    find ../../${ELDIR_REL}/lisp/g-client -maxdepth 1 -mindepth 1 -not -name '*.in' -not -name indent-files.el -exec ln -s {} \; 2>/dev/null
fi
for file in *.elc
do [ -e "${file%.elc}.el" ] || rm -f $file
done

cd ${ELCDIR}
if [ ${FLAVOR} != emacs ]; then
    for target in blurbs etc Makefile README media js servers sounds xsl
    do [ -e $target ] || ln -s ${ELDIR_REL}/$target
    done
fi
find -L . -type l -lname '*' -delete
touch .nosearch

make -ks EMACS=${FLAVOR} >compile.log 2>&1

find lisp -name '*~' -delete
if [ ${FLAVOR} != emacs ]
then rm -f Makefile lisp/Makefile
fi

gzip compile.log

echo "  Compilation log saved to ${ELCDIR}/compile.log.gz"

rm -rf ${GNUPGHOME}

exit 0
